/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbasico;

import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import javax.swing.JFileChooser;
import paintbasico.Lienzo.herramientas;


/**
 *
 * @author alejandro
 */
public class MiFrame extends javax.swing.JFrame {

    boolean verBarra;
    /**
     * Creates new form MiFrame
     */
    public MiFrame() {
        initComponents();
        verBarra = true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTipoDibujo = new javax.swing.ButtonGroup();
        PanelInferior = new javax.swing.JPanel();
        PanelColores = new javax.swing.JPanel();
        ColorNegro = new javax.swing.JButton();
        ColorRojo = new javax.swing.JButton();
        ColorAzul = new javax.swing.JButton();
        ColorBlanco = new javax.swing.JButton();
        ColorAmarillo = new javax.swing.JButton();
        ColorVerde = new javax.swing.JButton();
        BarraEstado = new javax.swing.JPanel();
        HerramientaSeleccionada = new javax.swing.JLabel();
        PanelRelleno = new javax.swing.JPanel();
        BotonRelleno = new javax.swing.JCheckBox();
        BarraHerramientas = new javax.swing.JToolBar();
        BotonLapiz = new javax.swing.JButton();
        BotonLinea = new javax.swing.JButton();
        BotonRectangulo = new javax.swing.JButton();
        BotonOvalo = new javax.swing.JButton();
        lienzo = new paintbasico.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        botonNuevo = new javax.swing.JMenuItem();
        botonAbrir = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verBarraEstado = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Básico");

        PanelInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelInferior.setPreferredSize(new java.awt.Dimension(433, 75));
        PanelInferior.setLayout(new java.awt.BorderLayout());

        PanelColores.setPreferredSize(new java.awt.Dimension(100, 50));
        PanelColores.setLayout(new java.awt.GridLayout(2, 0));

        ColorNegro.setBackground(new java.awt.Color(1, 1, 1));
        ColorNegro.setPreferredSize(new java.awt.Dimension(25, 25));
        ColorNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorNegroMouseClicked(evt);
            }
        });
        PanelColores.add(ColorNegro);

        ColorRojo.setBackground(new java.awt.Color(255, 0, 0));
        ColorRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorRojoMouseClicked(evt);
            }
        });
        PanelColores.add(ColorRojo);

        ColorAzul.setBackground(new java.awt.Color(1, 25, 250));
        ColorAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorAzulMouseClicked(evt);
            }
        });
        PanelColores.add(ColorAzul);

        ColorBlanco.setBackground(new java.awt.Color(254, 254, 254));
        ColorBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorBlancoMouseClicked(evt);
            }
        });
        PanelColores.add(ColorBlanco);

        ColorAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        ColorAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorAmarilloMouseClicked(evt);
            }
        });
        PanelColores.add(ColorAmarillo);

        ColorVerde.setBackground(new java.awt.Color(28, 255, 0));
        ColorVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorVerdeMouseClicked(evt);
            }
        });
        PanelColores.add(ColorVerde);

        PanelInferior.add(PanelColores, java.awt.BorderLayout.LINE_START);

        BarraEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BarraEstado.setPreferredSize(new java.awt.Dimension(429, 21));
        BarraEstado.setLayout(new java.awt.BorderLayout());

        HerramientaSeleccionada.setText("Barra de estado");
        BarraEstado.add(HerramientaSeleccionada, java.awt.BorderLayout.LINE_START);

        PanelInferior.add(BarraEstado, java.awt.BorderLayout.PAGE_END);

        PanelRelleno.setLayout(new java.awt.BorderLayout());

        BotonRelleno.setText("Relleno");
        BotonRelleno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRellenoMouseClicked(evt);
            }
        });
        BotonRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRellenoActionPerformed(evt);
            }
        });
        PanelRelleno.add(BotonRelleno, java.awt.BorderLayout.LINE_END);

        PanelInferior.add(PanelRelleno, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelInferior, java.awt.BorderLayout.PAGE_END);

        BarraHerramientas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BarraHerramientas.setRollover(true);
        BarraHerramientas.setPreferredSize(new java.awt.Dimension(100, 45));

        BotonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Lapiz.gif"))); // NOI18N
        BotonLapiz.setBorder(null);
        GrupoTipoDibujo.add(BotonLapiz);
        BotonLapiz.setFocusable(false);
        BotonLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLapiz.setPreferredSize(new java.awt.Dimension(36, 29));
        BotonLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLapiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLapizMouseClicked(evt);
            }
        });
        BarraHerramientas.add(BotonLapiz);

        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Linea.gif"))); // NOI18N
        BotonLinea.setBorder(null);
        GrupoTipoDibujo.add(BotonLinea);
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setPreferredSize(new java.awt.Dimension(36, 29));
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLineaMouseClicked(evt);
            }
        });
        BarraHerramientas.add(BotonLinea);

        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rectangulo.gif"))); // NOI18N
        BotonRectangulo.setBorder(null);
        GrupoTipoDibujo.add(BotonRectangulo);
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setPreferredSize(new java.awt.Dimension(36, 29));
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRectanguloMouseClicked(evt);
            }
        });
        BarraHerramientas.add(BotonRectangulo);

        BotonOvalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ovalo.gif"))); // NOI18N
        BotonOvalo.setBorder(null);
        GrupoTipoDibujo.add(BotonOvalo);
        BotonOvalo.setFocusable(false);
        BotonOvalo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonOvalo.setPreferredSize(new java.awt.Dimension(36, 29));
        BotonOvalo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonOvalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonOvaloMouseClicked(evt);
            }
        });
        BarraHerramientas.add(BotonOvalo);

        getContentPane().add(BarraHerramientas, java.awt.BorderLayout.PAGE_START);

        lienzo.setPreferredSize(new java.awt.Dimension(429, 250));

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        botonNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(botonNuevo);

        botonAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        botonAbrir.setText("Abrir");
        botonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(botonAbrir);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        verBarraEstado.setSelected(true);
        verBarraEstado.setText("Ver barra de estado");
        verBarraEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verBarraEstadoMouseClicked(evt);
            }
        });
        verBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraEstadoActionPerformed(evt);
            }
        });
        jMenu2.add(verBarraEstado);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorRojoMouseClicked
        lienzo.setColor(Color.red);
    }//GEN-LAST:event_ColorRojoMouseClicked

    private void ColorNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorNegroMouseClicked
        lienzo.setColor(Color.black);
    }//GEN-LAST:event_ColorNegroMouseClicked

    private void ColorAzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorAzulMouseClicked
        lienzo.setColor(Color.blue);
    }//GEN-LAST:event_ColorAzulMouseClicked

    private void ColorBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorBlancoMouseClicked
        lienzo.setColor(Color.white);
    }//GEN-LAST:event_ColorBlancoMouseClicked

    private void ColorAmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorAmarilloMouseClicked
        lienzo.setColor(Color.yellow);
    }//GEN-LAST:event_ColorAmarilloMouseClicked

    private void ColorVerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorVerdeMouseClicked
        lienzo.setColor(Color.green);
    }//GEN-LAST:event_ColorVerdeMouseClicked

    private void BotonLapizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLapizMouseClicked
        lienzo.setHerramientas(herramientas.LAPIZ);
        HerramientaSeleccionada.setText("Punto");
    }//GEN-LAST:event_BotonLapizMouseClicked

    private void BotonLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLineaMouseClicked
        lienzo.setHerramientas(herramientas.LINEA);
        HerramientaSeleccionada.setText("Línea");
    }//GEN-LAST:event_BotonLineaMouseClicked

    private void verBarraEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verBarraEstadoMouseClicked
        
    }//GEN-LAST:event_verBarraEstadoMouseClicked

    private void BotonRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRectanguloMouseClicked
        lienzo.setHerramientas(herramientas.RECTANGULO);
        HerramientaSeleccionada.setText("Rectángulo");
    }//GEN-LAST:event_BotonRectanguloMouseClicked

    private void BotonRellenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRellenoMouseClicked

    }//GEN-LAST:event_BotonRellenoMouseClicked

    private void BotonOvaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOvaloMouseClicked
        lienzo.setHerramientas(herramientas.OVALO);
        HerramientaSeleccionada.setText("Elipse");
    }//GEN-LAST:event_BotonOvaloMouseClicked

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        lienzo.limpiar();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void verBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraEstadoActionPerformed
        verBarra = !verBarra;
        BarraEstado.setVisible(verBarra);
    }//GEN-LAST:event_verBarraEstadoActionPerformed

    private void BotonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRellenoActionPerformed

        if(BotonRelleno.isSelected())
            lienzo.setRelleno(true);
        else
            lienzo.setRelleno(false);
         
    }//GEN-LAST:event_BotonRellenoActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraEstado;
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JButton BotonLapiz;
    private javax.swing.JButton BotonLinea;
    private javax.swing.JButton BotonOvalo;
    private javax.swing.JButton BotonRectangulo;
    private javax.swing.JCheckBox BotonRelleno;
    private javax.swing.JButton ColorAmarillo;
    private javax.swing.JButton ColorAzul;
    private javax.swing.JButton ColorBlanco;
    private javax.swing.JButton ColorNegro;
    private javax.swing.JButton ColorRojo;
    private javax.swing.JButton ColorVerde;
    private javax.swing.ButtonGroup GrupoTipoDibujo;
    private javax.swing.JLabel HerramientaSeleccionada;
    private javax.swing.JPanel PanelColores;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelRelleno;
    private javax.swing.JMenuItem botonAbrir;
    private javax.swing.JMenuItem botonNuevo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private paintbasico.Lienzo lienzo;
    private javax.swing.JCheckBoxMenuItem verBarraEstado;
    // End of variables declaration//GEN-END:variables
}
